### ISSUE TITLE
Port test for module

### ISSUE THREAD

**Issue by kleomash** [backdrop-contrib/filefield_paths#1]
The module was ported, but test not yet.

**Comment by indigoxela** [comment]
Some tests have been implemented.
Working tests are in file _filefield_paths.test_, the rest is pending or obsolete (needs verification).

**Comment by indigoxela** [comment]
Still work in progress...

All files in the /tests directory, that still contain "drupal_" need to get updated. Any volunteers? :stuck_out_tongue_winking_eye: I feel like I've done my share.

- filefield_paths.update.test
- pathauto.test
- redirect.test
- transliteration.test

**Comment by indigoxela** [comment]
While trying to get all tests working, it turned out that the retroactive processing of existing items didn't fully work.
A minor problem with the entity cache.
