### ISSUE TITLE
Support for CKEditor and IMCE paths (Feature Request)

### ISSUE THREAD

**Issue by schoenid** [backdrop-contrib/filefield_paths#13]
Using CKEditor I found that it is not possible to use the "File (Field) paths" module.
It would be nice, if Image and File Upload directories could also use this modules posibilities.
Is it possible to support it?

The same for IMCE, though it allows to configure subdirectories using user-variables and PHP (if one knows about how to use it).
It would be very practical, if everything could be configured the same way or even better on the same place.

However, the reason I ask is, I'm maintaining a website with 50+ users (amount is growing) which are creating content using CKEditor, so the site has already thousands of pictures in the image upload directory and hundreds of files in the file upload directory, which makes it nearly impossible, to find anything and it slows down the server.

I would be happy, if I could spread the images to content related directories, so a content for a specific group or book could be stored under its names directory.

**Comment by indigoxela** [comment]
> Using CKEditor I found that it is not possible to use the "File (Field) paths" module.

That's a bit tricky... As the name of this module suggests (File (Field) Paths), this module is supposed to deal with file fields. But CKEditor doesn't provide fields.

I'm not sure if it's possible (or even correct) to add this module's functionality to the format settings on, for example, /admin/config/content/formats/filtered_html.

**Comment by schoenid** [comment]
Thank you @indigoxela , I can see the problem.

Instead the configuration of globally usable paths should be possible, which then could be used by any other module or field. And your "File (Field) paths" module should be part of it. As I understand, this must be a core functionality or module. 

So I've posted a note to @jenlampton 's issue [Move file type settings to Configuration > Media](https://github.com/backdrop/backdrop-issues/issues/4583).
