### ISSUE TITLE
Upgrade from D7 to Backdrop - temporary files location missing

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/filefield_paths#14]
My D7 site had at this location:
admin/config/media/file-system/filefield-paths

this (default) setting for the temporary file location:
public://filefield_paths

I followed the upgrade process and encountered a problem with images in Paragraphs being uploaded to a strange location (system/temporary) and not to their intended directory (sites/default/files/images). Long story short, it turned out that the temporary files location in my upgraded site was blank.
I added the suggested "temporary://" at
admin/config/media/file-system/filefield-paths

and the images are now correctly uploaded to their target destination.

Credit goes to @argiepiano for spotting this.

**Comment by indigoxela** [comment]
@nattywebdev the value for file location is supposed to get set in an update hook: https://github.com/backdrop-contrib/filefield_paths/blob/1.x-1.x/filefield_paths.install#L71

If that value is empty on your install, something must have gone completely wrong when upgrading from D7. But there's nothing this module could do about that.
