### ISSUE TITLE
Updating to v1.x-1.0.2 results in AJAX HTTP error on 2 sites. Repeating running update.php, update goes through fine.

### ISSUE THREAD

**Issue by echozone** [backdrop-contrib/filefield_paths#19]
Updating to filefield_paths v1.x-1.0.2, on 2 local sites, update.php results in:

An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: PATH_TO/core/update.php?op=selection&token=TOKEN_HERE-op=do_nojs&op=do StatusText: Service unavailable (with message) ResponseText: Error: Call to undefined function filefield_paths_recommended_temporary_scheme() in filefield_paths_update_1001() (line 124 of /modules/filefield_paths/filefield_paths.install).

Then Status report indicates to run update.php again, the second time the update goes through fine on both sites.

**Comment by indigoxela** [comment]
> Error: Call to undefined function...

That rings a bell - didn't you struggle in other situations with "undefined function" problems?

The first thing to provide: Infos about your hosting. My suspicion is that the problems are caused by some specific setup in your hosting.

**Comment by echozone** [comment]
This was on 2 local installations on the latest version of MAMO Pro, v6.6. and PHP 4.7

Other modules have been updated without this issue.

That previous server issue was about certifications, and was resolved by the host AND also BD sites were moved to a modern new server.

I was putting off updating the two live sites, to see if this issue brought up anything.

**Comment by indigoxela** [comment]
@echozone many thanks for the info. :+1: 

Re the other reports I rather meant [this forum post](https://forum.backdropcms.org/forum/1231-update-results-call-undefined-function-fileneedstypeclassification), which seems very similar.

And I think it's php 7.4, not 4.7 :smile_cat:

**Comment by echozone** [comment]
OpCache that makes sense. Not sure if it was on before I messed with it before understanding, but it's off now. Closing...
